# Site config
url: https://dstudio.kr
highlighter: rouge
permalink: pretty
sass:
  sass_dir: assets/scss

collections:
  categories:
    output: true
    permalink: /categories/:path/
  tags:
    output: true
    permalink: /tags/:path/    

defaults:
  - scope:
      path: ''
      type: categories
    values:
      layout: categories
  - scope:
      path: ''
      type: tags
    values:
      layout: tag      
