url: https://likegyu.com

# variables
description: D studio


# File management
include: [".htaccess"]
exclude: ["README.md"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true