# User config
author: "D studio"
description: "D studio"
email: "admin.dstudio.kr"
instagram: "https://instagram.com/dstudio.kr"

# Site config
baseurl:
highlighter: rouge
permalink: pretty
sass:
  sass_dir: assets/scss
  style: compressed

collections:
  categories:
    output: true
    permalink: /categories/:path/
  tags:
    output: true
    permalink: /tags/:path/    

defaults:
  - scope:
      path: ''
      type: categories
    values:
      layout: categories
  - scope:
      path: ''
      type: tags
    values:
      layout: tag      