# User config
author: "D studio"
description: "D studio"
email: "admin.dstudio.kr"
instagram: "https://instagram.com/dstudio.kr"

# Site config
baseurl:
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

  images: 
  - image: /assets/images/apollo.jpg
  - image: /assets/images/apollo.jpg
  - image: /assets/images/apollo.jpg
  - image: /assets/images/apollo.jpg